from datetime import datetime

from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    PageBreak,
)

styles = getSampleStyleSheet()

title_style = styles["Title"]
title_style.alignment = TA_CENTER

heading_style = styles["Heading2"]
normal_style = styles["BodyText"]


def add_footer(canvas, doc):
    canvas.saveState()

    canvas.setFont("Helvetica", 9)

    canvas.drawString(
        40,
        25,
        "Generated by SentinelScan-AI v5"
    )

    canvas.drawRightString(
        560,
        25,
        f"Page {doc.page}"
    )

    canvas.restoreState()


def generate_pdf_report(
    target,
    risk_data,
    overall_risk,
    total_ports,
    open_ports,
    closed_ports,
    scan_time,
    ip_address,
):
    filename = f"reports/report_{target}.pdf"

    doc = SimpleDocTemplate(filename)

    story = []

    # -------------------------
    # Cover Page
    # -------------------------

    story.append(
        Paragraph(
            "SentinelScan-AI",
            title_style,
        )
    )

    story.append(
        Paragraph(
            "Professional Vulnerability Assessment Report",
            heading_style,
        )
    )

    story.append(Spacer(1, 30))

    story.append(
        Paragraph(
            f"<b>Target:</b> {target}",
            normal_style,
        )
    )

    story.append(
        Paragraph(
            f"<b>Resolved IP:</b> {ip_address}",
            normal_style,
        )
    )

    story.append(
        Paragraph(
            f"<b>Generated:</b> {datetime.now()}",
            normal_style,
        )
    )

    story.append(
        Paragraph(
            f"<b>Overall Risk:</b> {overall_risk}",
            normal_style,
        )
    )

    story.append(Spacer(1, 40))

    story.append(
        Paragraph(
            "Prepared using SentinelScan-AI",
            normal_style,
        )
    )

    story.append(PageBreak())

    # -------------------------
    # Scan Summary
    # -------------------------

    story.append(
        Paragraph(
            "Scan Summary",
            heading_style,
        )
    )

    summary = [
        ["Target", target],
        ["Resolved IP", ip_address],
        ["Ports Scanned", str(total_ports)],
        ["Open Ports", str(open_ports)],
        ["Closed Ports", str(closed_ports)],
        ["Scan Time", f"{scan_time} seconds"],
        ["Overall Risk", overall_risk],
    ]

    table = Table(summary, colWidths=[170, 300])

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (0, -1), colors.darkblue),
            ("TEXTCOLOR", (0, 0), (0, -1), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.grey),
            ("BACKGROUND", (1, 0), (1, -1), colors.beige),
            ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
        ])
    )

    story.append(table)

    story.append(PageBreak())

    # -------------------------
    # Findings
    # -------------------------

    story.append(
        Paragraph(
            "Open Port Findings",
            heading_style,
        )
    )

    findings = [["Port", "Service", "Risk"]]

    for item in risk_data:
        findings.append([
            str(item["port"]),
            item["service"],
            item["risk"],
        ])

    table = Table(findings)

    table.setStyle(
        TableStyle([
            ("BACKGROUND", (0, 0), (-1, 0), colors.darkred),
            ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
            ("GRID", (0, 0), (-1, -1), 1, colors.grey),
            ("BACKGROUND", (0, 1), (-1, -1), colors.whitesmoke),
            ("ALIGN", (0, 0), (-1, -1), "CENTER"),
        ])
    )

    story.append(table)

    story.append(PageBreak())

    # -------------------------
    # Recommendations
    # -------------------------

    story.append(
        Paragraph(
            "Security Recommendations",
            heading_style,
        )
    )

    recommendations = [
        "• Close unnecessary ports.",
        "• Restrict SSH access using firewall rules.",
        "• Keep exposed services updated.",
        "• Monitor authentication logs.",
        "• Disable unused services.",
        "• Perform regular vulnerability scans.",
    ]

    for rec in recommendations:
        story.append(
            Paragraph(rec, normal_style)
        )

    story.append(PageBreak())

    # -------------------------
    # Conclusion
    # -------------------------

    story.append(
        Paragraph(
            "Overall Assessment",
            heading_style,
        )
    )

    story.append(
        Paragraph(
            f"""
            The assessment identified
            <b>{open_ports}</b> open ports.

            Overall exposure level is
            <b>{overall_risk}</b>.

            Additional vulnerability testing is
            recommended for production systems.
            """,
            normal_style,
        )
    )

    doc.build(
        story,
        onFirstPage=add_footer,
        onLaterPages=add_footer,
    )

    print(f"[+] PDF Report Saved: {filename}")